// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  alternate_grid: defineAsyncComponent(
    () => import("./AlternateGrid/index.vue"),
  ),
  call_to_action: defineAsyncComponent(
    () => import("./CallToAction/index.vue"),
  ),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  hero_2: defineAsyncComponent(() => import("./Hero2/index.vue")),
  kit: defineAsyncComponent(() => import("./Kit/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
});
